version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3-stretch
    steps:
      - checkout
      - run:
          command: gem install bundler -v 1.17.3
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
          - gem-cache-v1-{{ checksum "Gemfile.lock" }}
          - gem-cache-v1-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                       --format RspecJunitFormatter \
                       --out test_results/rspec.xml \
                       --format progress \
                       $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

